apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demonutanix
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demonutanix
    spec:
      containers:
        - name: demonutanix
          image: pendril/demonutanix
          ports:
            - containerPort: 7000

---
apiVersion: v1
kind: Service
metadata:
  name: demonutanix-service
  labels:
    name: demonutanix-service
spec:
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: web
  selector:
    app: demonutanix
  type: LoadBalancer